name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'BREAKING CHANGES'
    labels:
      - 'BREAKING CHANGE'
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Fixes'
    labels:
      - 'fix'
      - 'bug'
      - 'security'
  - title: 'Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'
      - 'renovate'
  - title: 'Documentation'
    labels:
      - 'document'
      - 'documentation'
exclude-labels:
  - 'invalid'
  - 'internal-fix'
  - 'misc'
  - 'ci'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'BREAKING CHANGE'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'minor'
  patch:
    labels:
      - 'improvement'
      - 'fix'
      - 'bug'
      - 'security'
      - 'patch'
  default: patch
template: |
  [Compare $PREVIOUS_TAG with v$RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)

  ## Changes

  $CHANGES
