name: gh act tests
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ (github.event_name == 'pull_request' && github.head_ref) || github.ref }}
        fetch-depth: 0
    - name: Install act
      run: |
        curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
        echo "./bin" >> "${GITHUB_PATH}"
        {
          echo "-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest"
          echo "-P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04"
          echo "-P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04"
        } > .actrc
    - name: Install gh-act
      run: |
        make install
    - name: Dump github.event
      env:
        GITHUB_EVENT_CONTEXT: ${{ toJson(github.event) }}
      run: |
        echo "${GITHUB_EVENT_CONTEXT}" > github_event.json
    - name: Create act event.json
      run: |
        cat .git/config
        ls .git/refs/heads
        git rev-parse main
        gh act "${{ github.event_name }}" -n -e gh_act_event_raw.json
        jq . < gh_act_event_raw.json > gh_act_event.json
    - name: Diff
      run: |
        diff github_event.json gh_act_event.json || :
