name: Spec
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/spec.yml'

jobs:
  spec:
    name: spec on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm list -g
      - name: List installed packages
        if: runner.os == 'Linux'
        run: apt list --installed
      - name: Packages dependencies
        if: runner.os == 'Linux'
        run: apt-cache dotty
      - name: Check
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y apt-rdepends
          apt-rdepends libsecret-1-dev
      - name: test
        run: npm install @box/cli@3.16.0
