name: Spec
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/spec.yml'

jobs:
  spec:
    name: spec on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - run: npm list -g
      - name: List installed packages
        if: runner.os == 'Linux'
        run: apt list --installed
      - name: Packages dependencies
        if: runner.os == 'Linux'
        run: apt-cache depends --installed
