name: Spec
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/spec.yml'

jobs:
  spec:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - run: npm list -g
