name: workflow call test
on: 
  # pull_request:
  workflow_dispatch:

jobs:
  reusable_workflow_job:
    uses: srz-zumix/gh-act/.github/workflows/events.yml@test/debug_logging
    with:
      username: ${{ github.actor }}
    secrets: inherit
