name: workflow call test
on: 
  pull_request:
  workflow_dispatch:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: srz-zumix/gh-act/.github/workflows/events.yml@.
        with:
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
