name: workflow call test
on: 
  workflow_dispatch:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/events
        with:
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
